#version: 2.0

#Cayman theme (green)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Wayne Zhou's Portfolio]

#description: [Wayne Zhou's data analytics projects] #customize below
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/waynezhou39/" style="color:rgb(224,255,255); text-decoration:underline">LinkedIn</a> | 
  <a href="https://github.com/zz39/" style="color:rgb(224,255,255); text-decoration:underline">GitHub</a> | 
  <a href="https://github.com/zz39/resume/blob/main/About/Wayne_Zhou_Resume_2023.pdf" style="color:rgb(224,255,255); text-decoration:underline">Resume</a>
  </p>
  <p align="center">
  M.S. Computer Science at Northeastern University
  </p>

# light blue: , style="color:rgb(224,255,255);"
#rgb(255,160,122) LightSalmon
# turqouise: style="color:rgb(175,238,238);
#font-weight:bold

#Minimal theme (Blue and white)
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme

#title: [Computer Science Portfolio]
#description: [Wayne Zhou's data analytics projects]

  #theme source: https://pages.github.com/themes/ 

#theme: jekyll-theme-minimal

#minimal:
#  social_links:
#    - { platform: github,  user_url: "https://github.com/zz39/" }
#    - { platform: linkedin, user_url: "https://www.linkedin.com/in/waynezhou39/" }

